version: 1
formatters:
  simple:
    format: '%(asctime)s -%(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: main.log
    maxBytes: 2097152 # 2 MB in bytes
    backupCount: 1
  mqtt:
    class: AitiA.logger.Logger
    level: DEBUG
    formatter: simple
    filepath: AitiA/log_config.yaml
loggers:
  simpleExample:
    level: DEBUG
    handlers: [console, file, mqtt]
    propagate: no
root:
  level: DEBUG
  handlers: [console, file, mqtt]